name: 'Dependency Review'
on:
  push:
    branches:
      - master
  pull_request:
   types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest 

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high  # Will fail on high and critical severity vulnerabilities
          vulnerability-check: true
          comment-summary-in-pr: on-failure  # Adds a comment only if vulnerabilities are found
          comment-summary-in-pr: on-failure # Creates a summary report in case of failure
           fail-on-scopes: runtime
